### ISSUE TITLE
test OpenStack connector with IBM PowerVC

### ISSUE THREAD

**Issue by bassemelkhansa** [slipstream/SlipStream#108]
tasks: 
 - [x] connect to the powerVC via web interface
 - [x] connect to the power server via openVPN (using TunnelBlick GUI agent)
 - [x] connect to the power server via openVPN from a VM on the cloud(created via slipstream)
 - [x] verify connectivity between the VM and the POWER server via ping
 - [x] create an openstack instance on slipstream and configure it to be used with PowerVC
 - [ ] wait for the upgrade of keystone to v3.0 then, 
 - [ ] perform a lifecycle via the connector

**Comment by schaubl** [comment]
I resized this issue in waffle from 5 to 2

**Comment by schaubl** [comment]
I tested it and here are the outputs:
- :white_check_mark: VPN
- :white_check_mark: Web UI
- :o: API
  - :white_check_mark: I'm able to authenticate to the Identity service with v3 but
  - :x: The `catalog` part of the reply is missing so I cannot go further.

**Comment by loomis** [comment]
The technical contact at IBM is Thierry Huche (thierry.huche@fr.ibm.com).  Please contact him to get more information about their API and installation.
