### ISSUE TITLE
add elasticsearch to quick install

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStream#121]
Add elasticsearch to the deployment based on the quick install procedure.  The deployment should configure and start the service.  It should also limit access (via the firewall) to the ports used by elasticsearch to localhost.

(Eventually this would need to be extended to the full elasticsearch cluster when we move to a distributed deployment.)

**Comment by st** [comment]
test 
```
$ curl -O https://raw.githubusercontent.com/slipstream/SlipStream/feature/issue_%23121/install/slipstream.sh
$ chmod 755 sl*
$ ./slipstream.sh -k candidate -v -E
$ curl 'http://localhost:9200/?pretty'
...
last command should return JSON 
```

**Comment by st** [comment]
After changing centos-7 image size (2GB of RAM instead of 512M), and commented out call to `_configure_selinux`, test is OK.
