### ISSUE TITLE
Application workflow inheritance: multiple inheritance

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStream#125]
Allow for an application component to inherit from multiple application components.

``` text
my-app-component
    /    \
   /      \
 php     java
  |        |
  |        |
apache     |
   \      /
    \    /
     \  /
      \/
 ubuntu 16.04
```

This will have some requirements/limitations:
- The multiple inherited app-components should ends up in the same native image.
- If an image (in the split) has been build, it will not be always possible to use the builded image.
- The inherited app-components should have an order and this order have to be followed during workflow execution.

**Comment by bryan-brancotte** [comment]
Is some scenario where you have component A based on a specific image that is not present in all cloud, if you can to inherit from an component B you should say that you inherite from B, except the base image. Otherwise when based on a private image you will never be able to inherite from third party component.

```
important-image         random-image
     |                       X
     |                       X
    php                    java
     |                       |
     |                       |
   apache                    |
     |                       |
component A             component B
     |                       |
     \_________     _________/
               \   /
               |*  |
            results component (using parent of component A)
```

**Comment by schaubl** [comment]
still valid.
This issue should be taken into account when developping the CIMI `module` resource.

**Comment by schaubl** [comment]
Doesn't apply anymore.
