### ISSUE TITLE
Implement installation of Riemann on SlipStream server

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStream#127]
Part of US https://github.com/SixSq/NuvlaBox/issues/115

**Comment by konstan** [comment]
- listen on localhost:5666

**Comment by konstan** [comment]
@cal or @mebster Can you please answer to the question below?  Thanks.

There are three options when to install Riemann along with SlipStream server:

1. always
2. only with SS enterprise version
3. only when `nuvlabox` connector is selected to be installed (at the moment assumes enterprise SS)

Which one should be implemented?

**Comment by loomis** [comment]
I vote for #2 for now as the general functionality hinges on the service catalog, which is an enterprise-only feature.

**Comment by konstan** [comment]
Working in `issue_#127-install-rieman` branch.  This is the Riemann install script itself. 
https://github.com/slipstream/SlipStream/blob/issue_%23127-install-riemann/install/ss-install-riemann.sh

Will be plugging it into the global deployment flow when agreed on the option when to install the component.

**Comment by mebster** [comment]
I agree with Cal

**Comment by konstan** [comment]
@loomis and @mebster Thanks!

**Comment by konstan** [comment]
"Migration" requirement to be added to release notes:
- on SS enterprise edition one needs to download and run `https://github.com/slipstream/SlipStream/blob/master/install/ss-install-riemann.sh` to be able to see the on-/off-line state of the NuvlaBoxes.
