### ISSUE TITLE
Fail to map to output parameter of parent image

### ISSUE THREAD

**Issue by bryan-brancotte** [slipstream/SlipStream#167]
I have a Image A which inherite of P, and another image B. Let us consider that P have an output param outP, and B an input parameter inB.
I have a receipt where A and B should be there.
When I edit my receip and add A, I can map B.inB to A.outP, but not save, as displayed in attached image.

![image](https://cloud.githubusercontent.com/assets/11556772/18584294/0d01136a-7c10-11e6-9e52-8517e24b11f6.png)

**Comment by Josyab** [comment]
Hi guys, 

On Thursday i´ll be presenting the UC2 demo of the review in the Cloud Forward event. AFAIK this issue need to be solved in order to have a smooth demonstration. I am not sure the time required to solve it, but in case it´s feasible, it would be great if you can prioritize this issue.

**Comment by bryan-brancotte** [comment]
It works, thanks !
