### ISSUE TITLE
Placement policy not taken into account in deploy

### ISSUE THREAD

**Issue by bryan-brancotte** [slipstream/SlipStream#172]
With this [application](https://nuv.la/module/cyclone/UC2_Microbial_genomes_analysis/UC2-Demo-Brussels/5838#0-summary), I defined a "Placement policy" to "location='fr'" but when i deploy, exoscale is selected and not cyclon-fr2. Is it because cyclone-fr2 is not priced ?

Application:
![image](https://cloud.githubusercontent.com/assets/11556772/19273736/f10d1178-8fcd-11e6-929e-582d6eb2be1d.png)
After clicking on deploy:
![image](https://cloud.githubusercontent.com/assets/11556772/19273745/f885c5ee-8fcd-11e6-8f0d-fbad60fc1eff.png)

**Comment by st** [comment]
Placement policy filters out connectors before pricing is done.
It must be expressed at *component level* (there is a UI bug already known that let you enter this at application level but does not make sense yet).
Attribute to be filtered  must also be fully qualified: `schema-org:location='CH'` for one component.

**Comment by bryan-brancotte** [comment]
After discussions with @st here is a summary:

> At component level, it is possible to select only one cloud with a placement-policy with `connector/href='cyclone-fr2'` considering that the cloud is listed [https://nuv.la/api/service-offer](here)
