### ISSUE TITLE
Test Terraform support for Exoscale and OTC

### ISSUE THREAD

**Issue by 0xbase12** [slipstream/SlipStream#186]
# Overview
There are current limitations in our ability to manage VM lifecycle with Terraform on Exoscale and OTC.  This issue tracks these.

# Terraform Exoscale
The latest Exoscale plugin (0.8.0-rc1 not yet released) must used.  Here are the instructions for this workaround.  As soon as this version of the plugin is released, this workaround will not be required anymore.
## Abilities:
- [X] Create a VM
- [X] Delete a VM
## Install instruction
- Install [terraform version 0.8.0-rc1 or higher](https://releases.hashicorp.com/terraform/)
- Install [go compiler](https://golang.org/dl/)
- Compile [terraform-provider-exoscale plugin](https://github.com/exoscale/terraform-provider-exoscale)
- Once you have the binary of the plugin, put in your GOPATH and then Terraform will pick it up.
- Follow the blog [Adding an Exoscale virtual machine](https://www.exoscale.ch/syslog/2016/09/14/terraform-with-exoscale/) 

# Terraform OTC
Although the OpenStack Terraform plugin is working, on OTC we have an error that stops us from being able to create a VM.  We therefore currently do not have a workaround yet.
## Abilities:
- [ ] Create a VM
- [ ] Delete a VM
## Install instruction
- Install [terraform](https://releases.hashicorp.com/terraform/)
- Test config OTC example from this [github repository](https://github.com/OpenTelekomCloud/terraform-otc)
## OpenStack terraform plugin problem

Was able to create a network,  a subnet, a port, but when creating a VM it failed because he is not able to parse a response to OTC API:
```openstack_networking_network_v2.tf-net: Refreshing state... (ID: d185aa1e-e653-42a3-909d-ead38aa55a71)
openstack_compute_secgroup_v2.secgroup_1: Refreshing state... (ID: 20c167d2-7945-4b9c-8515-47e069dca17d)
openstack_networking_subnet_v2.tf-subnet: Refreshing state... (ID: 853c970e-cc52-4614-bc64-2740e2ee93d3)
openstack_networking_port_v2.port_1: Refreshing state... (ID: da98d70e-7c8b-4222-88a9-171549a24bed)
openstack_compute_instance_v2.tf-instance: Creating...
  access_ip_v4:               "" => "<computed>"
  access_ip_v6:               "" => "<computed>"
  flavor_id:                  "" => "<computed>"
  flavor_name:                "" => "m1.medium"
  image_id:                   "" => "<computed>"
  image_name:                 "" => "Standard_CentOS_7.2_latest"
  key_pair:                   "" => "lionel"
  name:                       "" => "tf-instance"
  network.#:                  "" => "1"
  network.0.access_network:   "" => "false"
  network.0.fixed_ip_v4:      "" => "<computed>"
  network.0.fixed_ip_v6:      "" => "<computed>"
  network.0.floating_ip:      "" => "<computed>"
  network.0.mac:              "" => "<computed>"
  network.0.name:             "" => "<computed>"
  network.0.port:             "" => "da98d70e-7c8b-4222-88a9-171549a24bed"
  network.0.uuid:             "" => "<computed>"
  security_groups.#:          "" => "1"
  security_groups.3913542647: "" => "20c167d2-7945-4b9c-8515-47e069dca17d"
  stop_before_destroy:        "" => "false"
Error applying plan:

1 error(s) occurred:

* openstack_compute_instance_v2.tf-instance: json: cannot unmarshal number 1.048576e+06 into Go value of type int

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.```

**Comment by 0xbase12** [comment]
## Retesting OTC
After Commits on Dec 1, 2016 in [githup otc terraform repo](https://github.com/OpenTelekomCloud/terraform-otc)

Actually we are able to create and delete VM. But, there is problem to get a public IP assigned to the VM. VMs are not accessible without a public IP.

Action needed from OTC to resolve networking issues

**Comment by konstan** [comment]
@0xbase12 Can this issue be closed?
