### ISSUE TITLE
CoTec TN5

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStream#222]
Write CoTec TN5: Data access analytics Technical Note

**Comment by mebster** [comment]
Under review by @loomis and then @konstan

**Comment by loomis** [comment]
I've finished my review. My comments and suggested changes are in the document.

**Comment by mebster** [comment]
Document delivered to ESRIN: https://www.dropbox.com/s/kf3bc1f9jxzj3ba/CoTec-TN5-v2.1.pdf?dl=0
