### ISSUE TITLE
Add pricing minimum period to the scrapers

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStream#233]
Exoscale charges per minute, compared to the standard 1 hour minimum charge.  This should be in part of offer metadata, such that it can be leveraged when creating policies.

**Comment by loomis** [comment]
This is already defined in the schema as `billingUnitCode`.  See the full schema [here](https://github.com/SixSq/SlipStreamPricing/blob/master/Schema.md). This should be provided by new scraper implementations.
