### ISSUE TITLE
Switch to JSON

### ISSUE THREAD

**Issue by rbf** [slipstream/SlipStream#26]
This is a top level issue to gather the points to amend and take into account to switch to JSON.
# Server
- [ ] If client requests JSON `dataType`, do not redirect and return HTML instead. (slipstream/SlipStreamServer#213)
# UI
- [ ] Request JSON `dataType` when the server correctly handles it.
  - [x] Reports resource

**Comment by schaubl** [comment]
UI uses now JSON for Reports. slipstream/SlipStreamServer@b46dcec2304b938150cce927c55be9ca535e17da and slipstream/SlipStreamServer@111a0aed05c1cf064c84a1f8b9a8e452fe6060bb.
Related: slipstream/SlipStreamServer#233
