### ISSUE TITLE
dashboard: List of deployments "hang" on loading after a Cloud has been selected.

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStream#306]
When looking at the requests, it appear that the request to load deployments is not made.
If I switch to the `Virtual Machines` tab and come back to the `Deployments` tab, then the request is made and it work.

**Comment by 0xbase12** [comment]
Done in following commits:
https://github.com/slipstream/SlipStreamWebUI/commit/12811e29f24ecf45a9ae13fcfb9f386628c1b9fc
https://github.com/slipstream/SlipStreamUI/commit/38fbad16188ae72afeba84502b90506f2377021f
