### ISSUE TITLE
New resource: Event

### ISSUE THREAD

**Issue by st** [slipstream/SlipStream#34]
#### Implementation
1. This will be a Clojure REST resource.
The flow for such a HTTP request will be:
Nginx -> RESTlet (forwards after authentication) ->  Ring -> Clojure Resource

2. Schema for this new resource should use the Event Resource from CIMI.
Details can be found here (section 5.17.13 Event Resource):
http://dmtf.org/sites/default/files/standards/documents/DSP0263_1.1.0.pdf

3. Layout of the URIs:
 .../events/type/uuid
e.g
 GET on .../events/run/7e91abca-a609-49b8-a081-459b2895ac87 will return all the events associated with the resource of typ run with uuid 7e91abca-a609-49b8-a081-459b2895ac87

**Comment by konstan** [comment]
amazing impersonalisation ... by waffle?! :-)
@st it wasn't me.
