### ISSUE TITLE
determine firewall configuration for CentOS 7

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStream#63]
The firewall commands have completely changed from CentOS 6 to CentOS 7.  The commands necessary to configure the firewall for SlipStream need to be worked out and added to the quick installation scripts.

**Comment by loomis** [comment]
The quick installation script will need to adapt to the firewall being used on the system.  Although `firewalld` is the standard for CentOS 7, the CentOS 7 image at Exoscale instead is configured to use the `iptables`.  The CentOS 7 image at Ultimum uses the default `firewalld`.

**Comment by schaubl** [comment]
@loomis @0xbase12 is it still an issue ?

**Comment by loomis** [comment]
No, this was corrected when migrating to CentOS 7.  It is tested through the deployment jobs on the CI.
