### ISSUE TITLE
add systemd configuration for CentOS 7

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStream#64]
CentOS 7 uses systemd rather than SystemV.  Add the systemd configuration files that are necessary to integrate the SlipStream services into systemd.  These will be ignored by CentOS 6, so this change will be compatible with CentOS 6 deployments.

**Comment by schaubl** [comment]
I think this has been done. @0xbase12 @loomis ?

**Comment by loomis** [comment]
Yes, this has been done.  It can be closed.
