### ISSUE TITLE
Allow to execute a script on the orchestrator

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStream#73]

**Comment by mebster** [comment]
Let discuss this!

**Comment by mebster** [comment]
After discussion with @konstan, we should have the following elements:
- add script to deployment module
- expose script in UI (create issue for that)
- execute script in orchestrator

**Comment by schaubl** [comment]
See the following tickets:
- https://github.com/slipstream/SlipStreamServer/issues/494
- https://github.com/slipstream/SlipStreamClient/issues/139
- https://github.com/slipstream/SlipStreamUI/issues/445
