### ISSUE TITLE
public networking fails for openstack

### ISSUE THREAD

**Issue by vincent-legoll** [slipstream/SlipStream#76]
I'm trying to get SlipStream (stable version) working with an openstack icehouse w/ neutron OVS production setup.

I'm finally able to instantiate VMs with private networking.

But if I start a VM with network type set to public, it won't start a I get this error message :
```
Error
ss:abort- 403 Forbidden It is not allowed to create an interface on external network 314be651-fcaa-4dcc-ac0a-dfdcd7e58ba1
```

I couldn't find how to make this work

**Comment by schaubl** [comment]
Hello,
I created a support ticket from your issue on http://support.sixsq.com.
I will reply from our ticketing system.

**Comment by vincent-legoll** [comment]
More precisely, [this ticket](http://support.sixsq.com/support/tickets/487).
