### ISSUE TITLE
update to clojure 1.6.0

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStream#8]
David Nolan has announced that the next release of ClojureScript will have a hard dependency on Clojure 1.6.0.  As we're planning on using ClojureScript for the UI, we should also update this dependency on the server side.

**Comment by schaubl** [comment]
I think it was already done.
@rbf @loomis Do you confirm ? If yes, you can close this issue.

**Comment by schaubl** [comment]
It looks like it has been updated to Clojure 1.7.0:
- https://github.com/slipstream/SlipStream/issues/60
- https://github.com/slipstream/SlipStream/pull/86
- https://github.com/slipstream/SlipStream/pull/87
