### ISSUE TITLE
VMs IPs never updated after first creation

### ISSUE THREAD

**Issue by 0xbase12** [slipstream/SlipStream#81]
Unlike the vmstate, the IP is set one time and never updated in SlipStream. 

When I change the network scenario in NuvlaBox, VMs  IPs change from one subnet to another. Currently IPs are updated in opennebula and in stratuslab but the update isn't propagated to SlipStream.

**Comment by schaubl** [comment]
To be able to update the IP we have to augment *-describe-instances to provide the IP.
At the same time we can provide even more informations (this can be useful/needed to provide more metrics for usages)
I would also suggest to update CLIs to return data as JSON.

**Comment by schaubl** [comment]
`*-describe-instances` commands were augmented to provide more informations.
But the IP wasn't added because there is no way to select the correct IP when multiple IPs are available.
The choice of the user (Public/Private) is not available in `*-describe-instances`.
